# Site settings
title: linuxiseasy - Linux docs
description: "A document about linux works and create customize linux ..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
#social url
slack_url: "https://linuxsh.slack.com/"
git_url: "https://github.com/linuxiseasy/linuxiseasy.github.io"
# Linuxsh iso location
_dev: "https://github.com/linuxiseasy/linuxiseasy.github.io/releases/latest"
_base: "https://github.com/linuxiseasy/linuxiseasy.github.io/releases/latest"
# source
_source: https://github.com/linuxiseasy/linuxiseasy.github.io

# top subject
top_subject:   :dizzy:Linuxsh is ready for use

#game section
# game top informatio
top_information: shut



# User settings
username: Linux
user_title: Linux Docs
email: linuxsh8@gmail.com
twitter_username: linuxiseasy
github_username:  linuxiseasy
gplus_username:  linuxiseasy
disqus_username: linuxiseasy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


gems:
  - jemoji


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: command line search
    url: /cs
  - title: Link Planet search
    url: /ls
  - title: about me
    url: /about
  - title: indexx
    url: /indexx
# projects in header index
projects:
  - name: Command Line Search
    url: /cs
  - name: Link Planet Search
    url: /ls
  - name: Linux Map
    url: /linuxmap
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']


