# Site settings
title: Linux Docs - rezaduty
description: "A document about linux works and create customize linux ..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://rezaduty.github.io/linuxsh" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
#social url
slack_url: "https://linuxsh.slack.com/"
git_url: "https://github.com/rezaduty/linuxsh/"
# Linuxsh iso location
_dev: "https://mega.nz/#!c7ImET7b!m24EZu-npO60SomMzX3avI5YlFSdPqu5DBBRXlsjlX4"
_base: "https://mega.nz/#!0iZ0kT5K!7nHI-RVuXXfFwaeoeppwjCz_AD2BJ2zwZloNiD6xsUM"
# source
_source: https://github.com/rezaduty/linuxsh

# top subject
top_subject:   :dizzy:Welcome Linuxsh

#game section
# game top informatio
top_information: shut



# User settings
username: Linux
user_title: Linux Docs
email: reza.duty.persian@gmail.com
twitter_username: rezaduty
github_username:  rezaduty
gplus_username:  rezaduty
disqus_username: rezaduty

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


gems:
  - jemoji


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: command line search
    url: /cs
  - title: Link Planet search
    url: /ls
  - title: about me
    url: /about
  - title: indexx
    url: /indexx
# projects in header index
projects:
  - name: Command Line Search
    url: /linuxsh/cs
  - name: Link Planet Search
    url: /linuxsh/ls
  - name: Linux Map
    url: /linuxsh/linuxmap
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']


